import type { LibraryEvent } from "./types";
import { getImage } from "./images";

export const events2022: LibraryEvent[] = [
  {
    name: "La licencia de Chevron",
    img: getImage(0),
    date: "2022-12-09",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Evanán Romero", "Rafael Gallegos", "Horacio Medina"],
    links: ["https://www.youtube.com/watch?v=xLWXehhN31w"],
  },
  {
    name: "Integrating Behind-the-Meter Solar Power In Upstream O&G Operations",
    img: getImage(1),
    date: "2022-12-02",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Alonzo A. Alvarez", "Ricardo Rangel (Chevron)"],
    links: ["https://www.youtube.com/watch?v=z9Q09d0X4MA&t=1s"],
  },
  {
    name: "La iniciativa latinoamericana y del Caribe para el mercado de carbono",
    img: getImage(2),
    date: "2022-11-18",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gladis Genua"],
    links: ["https://www.youtube.com/watch?v=K7RK4n4JW-c"],
  },
  {
    name: "Permitiremos que se pierda CITGO?",
    img: getImage(3),
    date: "2022-11-11",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12AM Venezuela",
    presenters: ["Horacio Medina"],
    links: ["https://www.youtube.com/watch?v=Dw8eHA9LSlI"],
  },
  {
    name: "La OPEP por dentro",
    img: getImage(4),
    date: "2022-11-04",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET/Venezuela)",
    presenters: ["Humberto Calderón Berti"],
    links: ["https://www.youtube.com/watch?v=zAvnlU1bE00"],
  },
  {
    name: "La Creación de Mundos",
    img: getImage(5),
    date: "2022-10-28",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET/Venezuela)",
    presenters: ["Eleodoro Ventocilla"],
    links: ["https://www.youtube.com/watch?v=5XzzWTcpIrU"],
  },
  {
    name: "Industrialización y Desindustrialización de Venezuela",
    img: getImage(6),
    date: "2022-10-21",
    type: "Webinar",
    time: "Fri 09AM (CT) - 10AM (ET) - Caracas 11AM",
    presenters: ["Gerardo Lucas"],
    links: ["https://www.youtube.com/watch?v=FyK8gP-udvw"],
  },
  {
    name: "Traspasando las fronteras: Como hacer oír la voz del Sector de Energía en Venezuela y el mundo",
    img: getImage(7),
    date: "2022-10-14",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Eduardo Betancourt"],
    links: ["https://www.youtube.com/watch?v=p-78PsNpYYU"],
  },
  {
    name: "Cambio Climático la Realidad, lo Inevitable y Futuros Posibles",
    img: getImage(8),
    date: "2022-10-07",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Fernando Miralles-Wilhelm"],
    links: ["https://youtu.be/z9y8SWQ3FFQ"],
  },
  {
    name: "Claves para Encender el Aparato Productivo",
    img: getImage(9),
    date: "2022-09-30",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Tomás Mata"],
    links: ["https://youtu.be/8_Ga1n4aWiM"],
  },
  {
    name: "El papel de los petroleros en la Reconstrucción de Venezuela",
    img: getImage(10),
    date: "2022-09-23",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Humberto Calderón Berti"],
    links: ["https://youtu.be/OSjlQ309jBg"],
  },
  {
    name: "Un Nuevo comienzo. Las Exportaciones Venezolanas",
    img: getImage(11),
    date: "2022-09-16",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Ricardo Cordido Martínez"],
    links: ["https://youtu.be/F1ftSCSYi6k"],
  },
  {
    name: "México: Contexto Actual e Incertidumbre",
    img: getImage(0),
    date: "2022-09-09",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Lucía Bustamante"],
    links: ["https://youtu.be/ek0A2fulNwU"],
  },
  {
    name: "El logro de la felicidad",
    img: getImage(1),
    date: "2022-09-02",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Jon Aizpúrua"],
    links: ["https://youtu.be/cUR0FO3xPF0"],
  },
  {
    name: "CITGO: VALOR DEL MAÑANA ESFUERZO DE HOY",
    img: getImage(2),
    date: "2022-08-26",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Horacio Medina"],
    links: ["https://youtu.be/Vo41xhFXEXo"],
  },
  {
    name: "Consideraciones sobre los gases de efecto invernadero en la industria petrolera",
    img: getImage(3),
    date: "2022-08-19",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Herman Rojas"],
    links: ["https://youtu.be/TtFVqJ-INJ0"],
  },
  {
    name: "El bloqueo de las potencias europeas a Venezuela en tiempos de Cipriano Castro",
    img: getImage(4),
    date: "2022-08-12",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Javier Escala Porras"],
    links: ["https://youtu.be/e1s4o15NG-E"],
  },
  {
    name: "¿Realmente tiene Venezuela las mayores reservas petroleras del mundo?",
    img: getImage(5),
    date: "2022-08-05",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Julián Salazar Velásquez"],
    links: ["https://youtu.be/lUUuKapb2rg"],
  },
  {
    name: "Gas Natural e Industria Siderúrgica en un entorno de Emisiones neutras 2050",
    img: getImage(6),
    date: "2022-07-29",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Víctor Vázquez"],
    links: ["https://youtu.be/hw4juZtzwJk"],
  },
  {
    name: "Doce competencias y su pertinencia en un mundo orgánico",
    img: getImage(7),
    date: "2022-07-22",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Arnaldo Gonzalez"],
    links: ["https://youtu.be/9u0H-h5b13s"],
  },
  {
    name: "La siembra de la pobreza",
    img: getImage(8),
    date: "2022-07-15",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Arquímedes Román"],
    links: ["https://youtu.be/5K5Dzj8h3EA"],
  },
  {
    name: "Rendición de Cuentas 2021–1T2022 PDVSA Ad Hoc CUMPLIENDO CON VENEZUELA",
    img: getImage(9),
    date: "2022-07-08",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Horacio Medina"],
    links: ["https://youtu.be/sHvVgHXjfuM"],
  },
  {
    name: "Los monstruos de la literatura",
    img: getImage(10),
    date: "2022-07-01",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["María Dolores Ara"],
    links: ["https://youtu.be/I0gU3EtE0Bw"],
  },
  {
    name: "Aspectos sobre la Participación Fiscal de los HC en Venezuela",
    img: getImage(11),
    date: "2022-06-24",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Jesus M. Aboud"],
    links: ["https://youtu.be/xESHLqEMLeE"],
  },
  {
    name: "Industria Eléctrica Venezolana: Transformación con Visión de Futuro",
    img: getImage(0),
    date: "2022-06-17",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Álvaro Yabel"],
    links: ["https://www.youtube.com/watch?v=IpMf_PgHRQY"],
  },
  {
    name: "AMÉRICA, ¿A DÓNDE VAS?",
    img: getImage(1),
    date: "2022-06-10",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Humberto Calderón", "Milos Alcalay", "Diego Arria", "Oracio medina"],
    links: ["https://www.youtube.com/watch?v=jLbRVRUbazk"],
  },
  {
    name: "Energy Security and Decarbonization Shifting Priorities in U S Energy Policy",
    img: getImage(2),
    date: "2022-06-03",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Jack Belcher"],
    links: ["https://www.youtube.com/watch?v=y5pdhtOydRA&t=11s"],
  },
  {
    name: "Orimulsión: pasado presente futuro",
    img: getImage(3),
    date: "2022-05-27",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Carlos Borregales Loaiza"],
    links: ["https://www.youtube.com/watch?v=j581HeaQD-I"],
  },
  {
    name: "El logro de la felicidad",
    img: getImage(4),
    date: "2022-05-20",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Jon Aizpúrua"],
    links: ["https://meet.goto.com/522683485"],
  },
  {
    name: "Proyecto Calidad de Yacimientos Terrígenos de las márgenes Caribe y Pacifico de Colombia",
    img: getImage(5),
    date: "2022-05-13",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Victor Ramírez"],
    links: ["https://www.youtube.com/watch?v=usBr5rfwjAg"],
  },
  {
    name: "Geopolítica Petrolera",
    img: getImage(6),
    date: "2022-05-06",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Humberto Calderón Berti"],
    links: ["https://www.youtube.com/watch?v=_TbQwPMHThU"],
  },
  {
    name: "Pre-OTC International Cocktail 2022",
    img: getImage(7),
    date: "2022-05-01",
    type: "Special Event",
    time: "Su 06:00PM to 09:00PM",
    presenters: [""],
    links: ["https://argentinatexas.org/event-4755495"],
  },
  {
    name: "Conversatorio con Maxim Ross sobre: El fin de Petrolia y una nueva Venezuela",
    img: getImage(8),
    date: "2022-04-29",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Maxim Ross"],
    links: ["https://www.youtube.com/watch?v=hX6z-Dt9jjg"],
  },
  {
    name: "Los logros de la Meritocracia Petrolera, Lecciones para el futuro de la Industria",
    img: getImage(9),
    date: "2022-04-22",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Rafael Gallegos"],
    links: ["https://www.youtube.com/watch?v=WuOA_Pjyl6g"],
  },
  {
    name: "Rómulo Gallegos / La rebelión",
    img: getImage(10),
    date: "2022-04-08",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["María Dolores Ara"],
    links: ["https://www.youtube.com/watch?v=du_BrvuqM_M"],
  },
  {
    name: "La Petroquímica como un elemento para el desarrollo sustentable de Venezuela, en el Marco de la Transición Energética",
    img: getImage(11),
    date: "2022-04-01",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["José Castor González"],
    links: ["https://www.youtube.com/watch?v=2A6bqzpkd6A"],
  },
  {
    name: "Experiencia Educativa: El Caso de Japón",
    img: getImage(0),
    date: "2022-03-25",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Ingrid Betancourt"],
    links: ["https://www.youtube.com/watch?v=8MYMXjQ95TQ"],
  },
  {
    name: "Alternativa Nuclear Dentro del Panorama Energético Global y Situación de Venezuela",
    img: getImage(1),
    date: "2022-03-18",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Rafael Martín"],
    links: ["https://www.youtube.com/watch?v=qvCs8oqIkFM"],
  },
  {
    name: "¿Es este el peor momento de nuestra historia? La coyuntura venezolana actual en perspectiva histórica",
    img: getImage(2),
    date: "2022-03-11",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Inés Quintero"],
    links: ["https://www.youtube.com/watch?v=ic5NP_EqAmk"],
  },
  {
    name: "Hydrocarbon Producers and the Path to Net Zero 2050",
    img: getImage(3),
    date: "2022-03-04",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Jessica Franquiz"],
    links: ["https://www.youtube.com/watch?v=srqXUASSHek"],
  },
  {
    name: "Proyecto Uverito (Venezuela) un sumidero de Carbono del CO2 atmosférico",
    img: getImage(4),
    date: "2022-02-25",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Juan F. Urich Portet", "Héctor Canales"],
    links: ["https://www.youtube.com/watch?v=Fqnj3qmtH7c&t=1619s"],
  },
  {
    name: "El fin de Petrolia y una nueva Venezuela",
    img: getImage(5),
    date: "2022-02-18",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Maxim Rose"],
    links: ["https://www.youtube.com/watch?v=mPMs3unKKZw"],
  },
  {
    name: "Cambio organizacional para el mejoramiento de la productividad",
    img: getImage(6),
    date: "2022-02-11",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Luis S. Vilora"],
    links: ["https://www.youtube.com/watch?v=xXRpdsAkG1o"],
  },
  {
    name: "Ideas para la Venezuela del Futuro",
    img: getImage(7),
    date: "2022-02-04",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Emilio Venuti"],
    links: ["https://www.youtube.com/watch?v=HgkRTcnNz0M&t=27s"],
  },
  {
    name: "Casas Muertas La promesa de resurrección. Una relectura de la novela de Miguel Otero Silva",
    img: getImage(8),
    date: "2022-01-28",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Milagros Socorro"],
    links: ["https://youtu.be/mjDf-ReW4Io"],
  },
  {
    name: "El talento humano en la recuperación de la Industria Energética Venezolana",
    img: getImage(9),
    date: "2022-01-14",
    type: "Webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - Caracas 12PM",
    presenters: ["Héctor Riquezes", "Nelsón Olmedillo", "Eduardo Betancourt"],
    links: ["https://youtu.be/pS4Yj6SHgaY"],
  },
];
