import type { LibraryEvent } from "./types";

export const events2020: LibraryEvent[] = [
  {
    name: "LINEAMIENTOS PARA LA RECONSTRUCCION DE LA CADENA FERRO SIDERURGICA",
    img: "./images/events/dec1820.png",
    date: "2020-12-18",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Victor Vazquez", "Teolindo Yanez e Ivan Sanojas"],
    links: ["https://www.youtube.com/watch?v=du3KgJCvtZ0&feature=youtu.be"],
  },
  {
    name: "REACTIVACION DEL SISTEMA NACIONAL DE REFINACION",
    img: "./images/events/dec1120.png",
    date: "2020-12-11",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Jorge Kamkoff", "Lino Carrillo y Rene Lucena"],
    links: ["https://www.youtube.com/watch?v=du3KgJCvtZ0&feature=youtu.be"],
  },
  {
    name: "REDUCCIÓN DE LA HUELLA DE CO2 MEDIANTE EL MONITOREO GEOFÍSICO DE LOS PROYECTOS DE EOR",
    img: "./images/events/dec0520.png",
    date: "2020-12-04",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Dr. Herminio Passalacqua"],
    links: ["https://www.youtube.com/watch?v=EG4eLzA34IE&feature=youtu.be"],
  },
  {
    name: "CONTRATACIONES PÚBLICAS TRANSPARENTES",
    img: "./images/events/nov2020.png",
    date: "2020-11-20",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Victor Hugo Rodriguez", "Oscar Castro Pacheco"],
    links: ["https://www.youtube.com/watch?v=i8AExdv3_Kg"],
  },
  {
    name: "CORONAVIRUS EN TIEMPOS DE CAMBIO",
    img: "./images/events/nov1320.png",
    date: "2020-11-13",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Dr. Luis Azpurua"],
    links: ["https://www.youtube.com/watch?v=MTXiknctb_o"],
  },
  {
    name: "IDEAS PARA REPOSICIONAR A VENEZUELA EN EL NUEVO MAPA ENERGETICO MUNDIAL",
    img: "./images/events/nov0620.png",
    date: "2020-11-06",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Tomas Mata"],
    links: ["https://www.youtube.com/watch?v=RxXJPmcewS8&feature=youtu.be"],
  },
  {
    name: "ORIGEN Y EVOLUCION DE CITGO",
    img: "./images/events/oct3020.png",
    date: "2020-10-30",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Carlos Jorda"],
    links: ["#."],
  },
  {
    name: "FORMACION DE CIUDADANOS UTILES, SOLUCION PARA VENEZUELA",
    img: "./images/events/oct2420.png",
    date: "2020-10-06",
    type: "webinar",
    time: " Sat 10AM - 11AM (CT)",
    presenters: [
      "Hector Riquezes",
      "Marisol Angarita",
      "Hector Rodriguez Manchego",
      "Maria Gabriela Pinto",
    ],
    links: ["https://www.youtube.com/watch?v=Tn15RIPcWE0"],
  },
  {
    name: "IMPORTANCIA DE PLANES DE DESARROLLO DE CAMPOS DE PETROLEO Y GAS",
    img: "./images/events/oct2320.png",
    date: "2020-10-23",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Julio Herbas"],
    links: ["https://www.youtube.com/watch?v=g-caZhdNI9o"],
  },
  {
    name: "RAZON DE SER",
    img: "./images/events/oct2220.png",
    date: "2020-10-22",
    type: "webinar",
    time: "Thu 10AM - 11AM (CT)",
    presenters: ["Alejandro Szilagyi"],
    links: ["https://www.youtube.com/watch?v=73GvhXRG9Sc"],
  },
  {
    name: "GERENCIA INTEGRADA DE CAMPOS AGOTADOS",
    img: "./images/events/oct0920.png",
    date: "2020-10-09",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Julian Salazar"],
    links: ["https://www.youtube.com/watch?v=-c_iRCQndQo"],
  },
  {
    name: "RECONSTRUCCIÓN, PETRÓLEO Y PARTICIPACIÓN NACIONAL",
    img: "./images/events/oct0220.png",
    date: "2020-10-02",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Antonio Vicentelli"],
    links: ["https://www.youtube.com/watch?v=0AJRU1xK7cg"],
  },
  {
    name: "FINANCING VENEZUELA OIL SECTOR POST-SANCTION",
    img: "./images/EventPlaceHolder2.png",
    date: "2020-09-25",
    type: "webinar",
    time: "Fri 11AM - 12PM (CT)",
    presenters: [
      "Ali Moshiri talks about Financing Venezuela Oil Sector Post-Sanction",
    ],
    links: ["#."],
  },
  {
    name: "VAPA - VENAMERICA WEBINAR",
    img: "./images/sep112020.png",
    date: "2020-09-11",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: [
      "Seguridad en el Proceso de Recuperacion de la Industria Petrolera en Venezuela",
      "",
      "Presentador: John Marulanda",
    ],
    links: ["https://www.youtube.com/watch?v=kddrsGG4mWQ"],
  },
  {
    name: "ESEQUIBO Y STABROEK : ENTRE LINEAS",
    img: "./images/eventplaceholdernull.png",
    date: "2020-08-28",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Presentador: Milton Mendez"],
    links: ["https://www.youtube.com/watch?v=bEY3k_T4vqo"],
  },
  {
    name: "DIAGNOSTICO Y SEGURIDAD EN VENEZUELA",
    img: "./images/events/eventplaceholdernull2.png",
    date: "2020-08-21",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Presentador: Ivan Simonovis"],
    links: ["https://www.youtube.com/watch?v=rFNLpZ2-9Po"],
  },
  {
    name: "EL NEGOCIO PETROLERO",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-08-14",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: [
      "Retos y Oportunidades - Exploración y Producción de Hidrocarburos No-Convencionales",
      "",
      "Presentador: Marcelo LaPrea-Bigott",
    ],
    links: ["https://www.youtube.com/watch?v=BTMzFUNxqlA"],
  },
  {
    name: "Usurpación vs Transición: el dilema venezolano",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-07-24",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Perkins Rocha"],
    links: ["https://www.youtube.com/watch?v=AOYGREcKSX0"],
  },
  {
    name: "Reboot Venezuelan Oil Industry: Lessons from other countries on the role of a Regulator",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-07-10",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Jan Paul Van Driel", "Adam Mitchel", "Jean-Jacques Lafon"],
    links: ["https://www.youtube.com/watch?v=U-sD-fh0NEY"],
  },
  {
    name: "Reforma Energetica Mexicana. Aprendizaje de la CNH y la Industria de la Informacion",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-07-08",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Jose Pablo Rinkenbach", "Juan Carlos Zepeda", "Oscar Roldan"],
    links: ["https://www.youtube.com/watch?v=zsdmxgNWk5o"],
  },
  {
    name: "Crisis Alimentarias en Venezuela . Propuesta de Superacion",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-07-03",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: [
      "Alirio Oliveros",
      "Luis Hidalgo Parisca",
      "Orlando Martinez Montilla",
    ],
    links: ["https://www.youtube.com/watch?v=GRfcU2jGM3E"],
  },
  {
    name: "Porque Colapso la Industria Petrolera Venezolana: Sobre esas experiencias y el modelo de captura de renta petrolera por parte del tesoro. ¿Qué caminos le restan a Venezuela para volver a ser un país exportador de petróleo?",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-06-26",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Alexander  Guerrero"],
    links: ["https://www.youtube.com/watch?v=EKQSqiY_6Xg"],
  },
  {
    name: "ONG Plan Pais: educando y conectando a jóvenes venezolanos",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-06-24",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Juan Pio Hernandez", "Carlos Ruiz"],
    links: ["https://www.youtube.com/watch?v=k13mMC7o2mg"],
  },
  {
    name: "Al Dia Siguiente",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-06-19",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Orlando Viera Blanco"],
    links: ["https://www.youtube.com/watch?v=I9hRZls5JPs"],
  },
  {
    name: "El Impacto de la Politica Economica y de las Instituciones en el Proceso de Desarrollo Venezolano - Lecciones para la Reconstruccion",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-06-12",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Miguel Rodriguez"],
    links: ["https://www.youtube.com/watch?v=W85ssbAuVqs"],
  },
  {
    name: "Transition Energetica de Venezuela",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-06-05",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Nelson Hernandez"],
    links: ["https://www.youtube.com/watch?v=FnxR4ZyLMJc"],
  },
  {
    name: "Mercado Interno Industria Petrolera Venezolana",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-06-03",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Ramon Catsro"],
    links: ["https://www.youtube.com/watch?v=GE6QILvOaGI"],
  },
  {
    name: "La Reconstruccion de Venezuela y el Rol de la Industria Petrolera",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-29",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Ricardo Hausmann"],
    links: ["https://youtu.be/aqe8iNdcpgI"],
  },
  {
    name: "La Pandemia y el Petroleo: El Caso de Venezuela",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-27",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Luis Giusti"],
    links: ["https://www.youtube.com/watch?v=_ORz6GWp9Do"],
  },
  {
    name: "Industria Venezolana de Hidrocarburos .  Regulacion Apropiada ?",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-22",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Cesar Mata Garcia"],
    links: ["https://www.youtube.com/watch?v=mI3BTz09lsc"],
  },
  {
    name: "Venezuela",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-20",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Miguel Rivero", "Toni"],
    links: ["https://www.youtube.com/watch?v=8KAgielT02M"],
  },
  {
    name: "Esquema Integrado de Seguridad Industrial y Ambiente para la reactivacion de la Industria Petrolera Venezolana",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-15",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Jorge Rodriguez Grau", "Luis Pabon"],
    links: ["https://youtu.be/GA3eX1ogvKo"],
  },
  {
    name: "La Industria petrolera y gasiferar venezolana del futuro.. Su potenciacion con base en  procesos ,tecnologias , organizacion y gente , y modelos de negocios y contratacion clase mundial",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-13",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: [
      "Freddy Perez",
      "Rafael Paz",
      "Giovanni Hernandez",
      "Adrian Sanchez",
    ],
    links: ["https://www.youtube.com/watch?v=ZJHlAaFVcCo"],
  },
  {
    name: "Plan Táctico de Emergencia para la IPPN",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-08",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Elizabeth Cruz"],
    links: ["https://www.youtube.com/watch?v=SaP8Dz9kkHg"],
  },
  {
    name: "Venezuela : El Desafio del Sector Petrolero",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-06",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Reinaldo Quintero"],
    links: ["https://youtu.be/UBal_vr1BSU"],
  },
  {
    name: "Hacia una Nueva IPN - Tiempo de Nuevas Ideas",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-05-01",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Luis Pacheco", "Juan Szabo"],
    links: [
      "https://youtu.be/UBal_vr1BSU",
      "https://www.youtube.com/watch?v=ZJHlAaFVcCo",
    ],
  },
  {
    name: "La nueva LOH Mitos y Realidades",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-04-29",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Luis Stefanelli"],
    links: [
      "https://youtu.be/32uRtz8n7YU",
      "https://youtu.be/K8jSIyS7OCo",
      "https://www.youtube.com/watch?v=TLYDJE2r1lA",
    ],
  },
  {
    name: "Un Nuevo Marco Institucional, Fiscal y Contractual para la Industria Petrolera Venezolana",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-04-24",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Francisco Monaldi"],
    links: [
      "https://youtu.be/LkITFobgISw",
      "https://www.youtube.com/watch?v=FvtO1iYkMoQ",
    ],
  },
  {
    name: "Problematica del Suministro de Combustible al Mercado Interno de Venezuela",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-04-22",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: [
      "Jorge Kamkoff",
      "Rene Lucena",
      "Francois Raineau",
      "Rene Lucene",
      "Francois Raineau",
    ],
    links: [
      "https://youtu.be/y0NOTy3Wxmc",
      "https://www.youtube.com/watch?v=uGd7JwYe78A",
    ],
  },
  {
    name: "Aspectos Relevantes del Plan de Recuperaciondel Sector Electrico Venezolano - VESRP",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-04-17",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Miguel Lara", "Jose Aguilar"],
    links: [
      "https://youtu.be/kOBwrXX9QNQ",
      "https://youtu.be/FE94ID54dxQ",
      "https://www.youtube.com/watch?v=sPw8fapYi5I",
    ],
  },
  {
    name: "Un plan para recuperar el sector petróleo y gas con base a 100% esfuerzo privado",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-04-10",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Evanan Romero"],
    links: [
      "https://youtu.be/ZXxvnVch32Q",
      "https://youtu.be/vh-MjnRF3n8",
      "https://www.youtube.com/watch?v=yYtnbVPYat8",
    ],
  },
  {
    name: "Me acaban de nombrar Ministro de Energía y el Presidente me pregunta: Qué vamos a hacer en los próximos 6 meses? Esta es mi respuesta",
    img: "./images/eventplaceholdernull2.png",
    date: "2020-04-03",
    type: "webinar",
    time: "FRI 10AM - 11AM (CT)",
    presenters: ["Humberto Calderon Berti", "Horacio Medina", "Eugenio Montoro"],
    links: [
      "https://youtu.be/2JfO5_Q4zAM",
      "https://youtu.be/LX7BdIkdHEc",
      "https://youtu.be/-NS7oIMBaUU",
      "https://youtu.be/XR7SxSiGX0Q",
      "https://youtu.be/h1debFvKnjA",
    ],
  },
];
