import type { LibraryEvent } from "./types";
import { getImage } from "./images";

export const events2021: LibraryEvent[] = [
  {
    name: "CAREER AND TECHNICAL MENTORSHIP PROGRAM",
    img: getImage(0),
    date: "2021-12-31",
    type: "webinar",
    time: "",
    presenters: [],
    links: ["mentorship.html"],
  },
  {
    name: "La transición Energética, Plataforma para la nueva gran expansión de Venezuela",
    img: getImage(1),
    date: "2021-12-03",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Tomas Mata"],
    links: ["https://youtu.be/me2HbhmT5Uc"],
  },
  {
    name: "PROTECCIÓN AMBIENTAL EN LA IPN: LO QUE LOGRAMOS Y UNA PROPUESTA CONCEPTUAL PARA LA ACCIÓN FUTURA",
    img: getImage(2),
    date: "2021-11-19",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Juan F Urich", "Sergio R Alcalá"],
    links: [""],
  },
  {
    name: "Venezuela: La Transición Energética y Energías Renovables",
    img: getImage(3),
    date: "2021-11-12",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Nelson Hernández"],
    links: [""],
  },
  {
    name: "Gerencia de crisis, liderar en desafíos",
    img: getImage(4),
    date: "2021-11-05",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Arnaldo Rodríguez"],
    links: ["https://youtu.be/IlMU3-fUMFY"],
  },
  {
    name: "La Economía del Hidrógeno y la Importancia del Almacenamiento en el Subsuelo",
    img: getImage(5),
    date: "2021-10-22",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Lorena Moscardelli"],
    links: ["https://youtu.be/-rf5c3Qe98g"],
  },
  {
    name: "SPE-GCS Hiring Event",
    img: getImage(6),
    date: "2021-10-12",
    type: "special_event",
    time: "THU-FRI 08:00AM - 04:00PM (CT)",
    presenters: [""],
    links: [
      "https://www.linkedin.com/posts/spe-gcs-hiring-event_spegcshiringevent-hiring-opportunity-activity-6841485861008351232-Byzq",
    ],
  },
  {
    name: "La Geotermia, La renovable más afín a la Industria del Petróleo",
    img: getImage(7),
    date: "2021-10-08",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Reinaldo Ramirez"],
    links: ["https://youtu.be/AsTmpSwQlf8"],
  },
  {
    name: "Campo Jay-Lec, un buen ejemplo de una exitosa gerencia de yacimientos",
    img: getImage(8),
    date: "2021-10-01",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Ricardo Padrón"],
    links: ["https://youtu.be/eeOv6tpVM2w"],
  },
  {
    name: 'PROYECTO "SOSTENIBILIDAD"',
    img: getImage(9),
    date: "2021-09-24",
    type: "special_event",
    time: "THU-FRI 08:15AM - 12:30PM (CT)",
    presenters: [""],
    links: ["sustainability.html"],
  },
  {
    name: "Reinserción de Venezuela en los mercados de crudos: Una teoría",
    img: getImage(10),
    date: "2021-09-24",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Tyrone Perdomo"],
    links: ["https://youtu.be/sVecMhRbnqU"],
  },
  {
    name: "Las dos grandes amenazas actuales a la industria petrolera: el antifracking y el calentamiento global",
    img: getImage(11),
    date: "2021-09-17",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Julian Salazar"],
    links: ["https://youtu.be/sVecMhRbnqU"],
  },
  {
    name: "Retos para integrar el petróleo a la economía circular de los plásticos",
    img: getImage(0),
    date: "2021-09-10",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Freddy Goerke García"],
    links: ["https://global.gotomeeting.com/join/767711269"],
  },
  {
    name: "Tecnologías para Incremento de Recobro y Mejoramiento In Situ de Crudos Pesados",
    img: getImage(1),
    date: "2021-09-03",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Pedro Pereira"],
    links: ["https://youtu.be/qcxiIy6Jeik"],
  },
  {
    name: "Fundamentos de la Gerencia del Cambio",
    img: getImage(2),
    date: "2021-08-27",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Eduardo Betancourt"],
    links: ["https://youtu.be/dYwcDIzEN94"],
  },
  {
    name: "La ética en una nueva cultura organizacional para la Industria Energética Venezolana",
    img: getImage(3),
    date: "2021-08-20",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Vinicio Semprún"],
    links: ["https://youtu.be/2aV6Frd8eW0"],
  },
  {
    name: "Herramientas para fortalecer el Liderazgo Propositivo ante la nueva realidad organizacional",
    img: getImage(4),
    date: "2021-08-13",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Ángel Ceballos"],
    links: ["https://youtu.be/ASoBRmdiKso"],
  },
  {
    name: "Gerencia integrada de yacimientos",
    img: getImage(5),
    date: "2021-08-06",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Claudio Martínez"],
    links: ["https://youtu.be/1M9RdfAQzk4"],
  },
  {
    name: "New and Improved In-situ Recovery Methods for Oil Sands and Heavy Oil",
    img: getImage(6),
    date: "2021-07-30",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Dr Thomas Harding"],
    links: ["https://youtu.be/iGgL2Wk6crQ"],
  },
  {
    name: "La Transición Energética y su impacto en la Ingeniería de Petróleo",
    img: getImage(7),
    date: "2021-07-23",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Nelson Hernández"],
    links: ["https://youtu.be/twP4p5JhLFE"],
  },
  {
    name: "ESG y otros acrónimos claves para petróleo y gas",
    img: getImage(8),
    date: "2021-07-16",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["María Ángela Capello"],
    links: ["https://global.gotomeeting.com/join/671481605"],
  },
  {
    name: "Aprendizajes para avanzar",
    img: getImage(9),
    date: "2021-07-09",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Luis Pulgar"],
    links: ["https://global.gotomeeting.com/join/325279629"],
  },
  {
    name: "Béisbol en tiempos de Transformación",
    img: getImage(10),
    date: "2021-07-02",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Claudio Martínez"],
    links: ["https://global.gotomeeting.com/join/398741533"],
  },
  {
    name: "Mega Tendencias, Mega Realidades y Mega Rupturas: 2040",
    img: getImage(11),
    date: "2021-06-25",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Antonio Vincentelli"],
    links: ["https://global.gotomeeting.com/join/129930029"],
  },
  {
    name: "Caracterización de Yacimientos Fracturados Complejos",
    img: getImage(0),
    date: "2021-06-18",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["José Guzmán"],
    links: ["https://global.gotomeeting.com/join/838961213"],
  },
  {
    name: "La IV Revolución Industrial y el Paradigma Emergente en la Gestión de RR.HH",
    img: getImage(1),
    date: "2021-06-11",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Paul Rosillón"],
    links: ["https://global.gotomeeting.com/join/954816125"],
  },
  {
    name: "First EAGE/VAPA Online Forum: Venezuela's Upstream to Downstream",
    img: getImage(2),
    date: "2021-06-03",
    type: "special_event",
    time: "THU-FRI 08:15AM - 12:30PM (CT)",
    presenters: [""],
    links: [
      "https://eage.eventsair.com/first-eagevapa-online-forum-venezuelas-upstream-to-downstream-past-present-and-future/",
    ],
  },
  {
    name: "Venezuela: Energy Solutions for the future",
    img: getImage(3),
    date: "2021-06-01",
    type: "webinar",
    time: "Online Final",
    presenters: [""],
    links: ["https://www.venezuelaenergy.org/"],
  },
  {
    name: "La Industria Energética: Plataforma para la Prosperidad de Venezuela",
    img: getImage(4),
    date: "2021-05-28",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Tomas Mata"],
    links: ["https://youtu.be/W3TxpIAHh9s"],
  },
  {
    name: "Interpretar y Actuar en el Mundo de Hoy",
    img: getImage(5),
    date: "2021-05-21",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Sergio Maggiolo"],
    links: ["https://youtu.be/eu0dSfA4F4Q"],
  },
  {
    name: "Sostenibilidad en La Industria de Petróleo y Gas",
    img: getImage(6),
    date: "2021-05-14",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Irene Petkoff"],
    links: ["https://youtu.be/nnSX-lMrTjw"],
  },
  {
    name: "Una visión de los Estados Unidos de América para la Reconstrucción del Sector Energético Venezolano",
    img: getImage(7),
    date: "2021-05-12",
    type: "webinar",
    time: "Wed 3PM (CT) - 4PM (ET)",
    presenters: ["James Story"],
    links: ["https://youtu.be/nnSX-lMrTjw"],
  },
  {
    name: "El movimiento sindical ante las nuevas realidades",
    img: getImage(8),
    date: "2021-04-30",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET)",
    presenters: ["Carlos Ortega", "León Arismendi", "Carlos Henríquez"],
    links: ["https://youtu.be/jgJ4rbFzxOA"],
  },
  {
    name: "El sur del orinóco, el alma económica de Venezuela",
    img: getImage(9),
    date: "2021-04-29",
    type: "webinar",
    time: "Thu 10AM (CT) - 11AM (ET)",
    presenters: ["Jorge Trujillo Herrera"],
    links: ["https://youtu.be/l-8NzNWR83M"],
  },
  {
    name: "La felicidad en el trabajo. Trabájate mientras trabajas",
    img: getImage(10),
    date: "2021-04-23",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Dorian Oria"],
    links: ["https://youtu.be/-aN8XrhZPbI"],
  },
  {
    name: "XVI CONGRESO VENEZOLANO DE GEOFISICA",
    img: getImage(11),
    date: "2021-02-24",
    type: "webinar",
    time: "Wed-Fri 10AM - 06PM (CT)",
    presenters: ["SOVG"],
    links: ["specialevent.html"],
  },
  {
    name: "LOS RETOS ORGANIZACIONALES Y DE CAPITAL HUMANO DE LA NUEVA IPN",
    img: getImage(0),
    date: "2021-02-12",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Eduardo Betancourt"],
    links: ["https://global.gotomeeting.com/join/630750581"],
  },
  {
    name: "SISTEMA INTEGRADO PARA LA GESTIÓN DEL RIESGO EN PROYECTOS DE CAPITAL Y DESMANTELAMIENTO",
    img: getImage(1),
    date: "2021-01-22",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Asdrubal Medina"],
    links: ["https://www.youtube.com/watch?v=2BwzqmM1XrU&feature=youtu.be"],
  },
  {
    name: "USO DE DATOS SÍSMICOS PARA LA CONSTRUCCIÓN DE MODELOS DE FLUJO EN YACIMIENTOS FRACTURADOS NO CONVENCIONALES",
    img: getImage(2),
    date: "2021-01-15",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Dr. Reinaldo Michelena"],
    links: ["https://www.youtube.com/watch?v=ar64fdr0k0Y&feature=youtu.be"],
  },
  {
    name: "SUSTAINABLE ENERGY FOR THE 21ST CENTURY",
    img: getImage(3),
    date: "2021-01-08",
    type: "webinar",
    time: "Fri 10AM - 11AM (CT)",
    presenters: ["Dr. Scott Tinker"],
    links: ["https://www.youtube.com/watch?v=RSqJ24HOWjo&feature=youtu.be"],
  },
];
