import type { LibraryEvent } from "./types";
import { getImage } from "./images";

export const events2023: LibraryEvent[] = [
  {
    name: "La ruta para reinventar a Venezuela. PETRÓLEO Piedra Angular del Desarrollo",
    img: getImage(0),
    date: "2023-12-08",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Tomás Mata"],
    links: ["https://www.youtube.com/watch?v=oI7zCkMRVMQ"],
  },
  {
    name: "¿Tiene sentido hablar de reservas (como en la industria petrolera) con energías renovables?",
    img: getImage(1),
    date: "2023-12-01",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Enzo Aconcha"],
    links: ["https://youtu.be/O-yebUXSe0E"],
  },
  {
    name: "Así perdimos el Esequibo",
    img: getImage(2),
    date: "2023-11-17",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Dr. Asdrúbal Aguiar"],
    links: ["https://youtu.be/RGDYq2zuU3k"],
  },
  {
    name: "El mercado petrolero, una conversación a dos voces",
    img: getImage(3),
    date: "2023-11-10",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Luis Pacheco", "M. Juan Szabo"],
    links: ["https://youtu.be/oQSoNqA5Hjc"],
  },
  {
    name: "Seguridad Psicológica",
    img: getImage(4),
    date: "2023-11-03",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Miguel González"],
    links: ["https://www.youtube.com/watch?v=Ey3DuuoSoaw"],
  },
  {
    name: "Geopolítica Energética",
    img: getImage(5),
    date: "2023-10-27",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Ricardo Colmenter"],
    links: ["https://www.youtube.com/watch?v=4Su6BKIU3Jw"],
  },
  {
    name: "Esquemas de desarrollo de la energía geotérmica",
    img: getImage(6),
    date: "2023-10-20",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Reinaldo Ramírez"],
    links: ["https://www.youtube.com/watch?v=KKs_9qLIlAI"],
  },
  {
    name: "EL UMBRAL CUÁNTICO",
    img: getImage(7),
    date: "2023-10-13",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Eleodoro Ventocilla"],
    links: ["https://www.youtube.com/watch?v=g5tHdofdLfU"],
  },
  {
    name: "Recuperación del bienestar colectivo en Venezuela y rol de las energías vía autopista o carretera",
    img: getImage(8),
    date: "2023-10-06",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gustavo García"],
    links: ["https://www.youtube.com/watch?v=QKnyk54N6Kg"],
  },
  {
    name: "Francisco de Miranda, la Libertad y los Estados Unidos",
    img: getImage(9),
    date: "2023-09-29",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Luis Xavier Grisanti"],
    links: ["https://www.youtube.com/watch?v=n6qcC04qayk"],
  },
  {
    name: "Propuesta de Programa Energético para Venezuela",
    img: getImage(10),
    date: "2023-09-22",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Eduardo Betancourt"],
    links: ["https://www.youtube.com/watch?v=IaHuQMGuH34"],
  },
  {
    name: "La privatización de facto de PDVSA y la crisis de Citgo",
    img: getImage(11),
    date: "2023-09-15",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["José Ignacio Hernández"],
    links: ["https://www.youtube.com/watch?v=-ym3pt04-Vw"],
  },
  {
    name: "Aspectos legales de la Transformación Digital en Petróleo y Gas",
    img: getImage(0),
    date: "2023-09-08",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gabriela Rachadell de Delgado"],
    links: ["https://www.youtube.com/watch?v=Y9zVLBbILsk"],
  },
  {
    name: "Crecimiento, energía y ambiente en la encrucijada",
    img: getImage(1),
    date: "2023-09-01",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Antonio Vincentelli"],
    links: ["https://www.youtube.com/watch?v=ad281Oh3G4Y"],
  },
  {
    name: "Energía post dictadura 2025 2031 y plan de recuperación de dos décadas perdidas",
    img: getImage(2),
    date: "2023-08-25",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Evanan Romero"],
    links: ["https://www.youtube.com/watch?v=DgOxqw-s7vw"],
  },
  {
    name: "Prospects for Venezuelan Debt Restructuring and Economic Reconstruction",
    img: getImage(3),
    date: "2023-08-18",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Steven T. Kargman"],
    links: ["https://www.youtube.com/watch?v=doQDllNWzpw"],
  },
  {
    name: "¿Cómo traer luz al Zulia?",
    img: getImage(4),
    date: "2023-08-11",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Tomás Mata"],
    links: ["https://www.youtube.com/watch?v=O0CIM2ZJG1I"],
  },
  {
    name: "Necesidades Energéticas de Venezuela Transformando con Visión de Futuro",
    img: getImage(5),
    date: "2023-08-04",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Alvaro Yaber"],
    links: ["https://youtu.be/p0_YcYa3gt0"],
  },
  {
    name: "Economía del Hidrógeno y rol del Almacenamiento Geológico",
    img: getImage(6),
    date: "2023-07-28",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Lorena Moscardelli"],
    links: ["https://youtu.be/Teiad_zbiQ4"],
  },
  {
    name: "Proceso de Internacionalización",
    img: getImage(7),
    date: "2023-07-21",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Luis Xavier Grisanti"],
    links: ["https://www.youtube.com/watch?v=bZmJ0Z5pOGM"],
  },
  {
    name: "Gas natural de Venezuela: Retos y Oportunidades con Trinidad y Tobago",
    img: getImage(8),
    date: "2023-07-14",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Horacio Medina"],
    links: ["https://www.youtube.com/watch?v=_qrX_sHdEwk"],
  },
  {
    name: "¿Qué está pasando en Citgo?",
    img: getImage(9),
    date: "2023-07-07",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Horacio Medina"],
    links: ["https://www.youtube.com/watch?v=rHVta8DxPi4"],
  },
  {
    name: "Potencial del sector forestal para la mitigación del cambio climático en Venezuela",
    img: getImage(10),
    date: "2023-06-30",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["José Rafael Lozada"],
    links: ["https://www.youtube.com/watch?v=nRiv0WBuiTg"],
  },
  {
    name: "Energía, política, pobreza y sostenibilidad",
    img: getImage(11),
    date: "2023-06-23",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Eduardo Betancourt"],
    links: ["https://www.youtube.com/watch?v=1uhjBzXJ6-0"],
  },
  {
    name: "Venezuela: Polo Energético e Industrial de Bajas Emisiones de las Américas",
    img: getImage(0),
    date: "2023-06-17",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Lino Carrillo"],
    links: ["https://www.youtube.com/watch?v=s_OIWI_m3aM"],
  },
  {
    name: "Perspectivas Económicas de Venezuela",
    img: getImage(1),
    date: "2023-06-09",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Luis Oliveros"],
    links: ["https://www.youtube.com/watch?v=tydl-4jvAl8"],
  },
  {
    name: "Toma de Decisiones Multi criterio en la industria de Petróleo y Gas",
    img: getImage(2),
    date: "2023-06-02",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Asdrúbal Perozo"],
    links: ["https://www.youtube.com/watch?v=0t4Pekjyt48"],
  },
  {
    name: "Responsabilidad social de nuestra industria petrolera 1920-2022",
    img: getImage(3),
    date: "2023-05-26",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Eddie Ramirez"],
    links: ["https://www.youtube.com/watch?v=1uhjBzXJ6-0"],
  },
  {
    name: "Venezuela y su relación con los hidrocarburos, el juego cambia de \"Suma Cero\" a \"Suma Positiva\". Nuevo Marco Fiscal",
    img: getImage(4),
    date: "2023-05-19",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Javier Rodríguez"],
    links: ["https://www.youtube.com/watch?v=bFI63EEIaMA"],
  },
  {
    name: "Planificación del Desarrollo de Campos de Petróleo y Gas",
    img: getImage(5),
    date: "2023-05-12",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Claudio Martínez"],
    links: ["https://www.youtube.com/watch?v=BJK8qFU5d-8"],
  },
  {
    name: "Qué hacer con la industria petrolera",
    img: getImage(6),
    date: "2023-05-05",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Rafael Gallegos"],
    links: ["https://www.youtube.com/watch?v=QPDTHvfArb8"],
  },
  {
    name: "Hidrocarburos, nuevo orden y descarbonización",
    img: getImage(7),
    date: "2023-04-21",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Luis Xavier Grisanti"],
    links: ["https://www.youtube.com/watch?v=9IrGpw4kLZk"],
  },
  {
    name: "Sector Energético Venezolano: ¿Cómo lograr claridad de acción? ¿Cómo llegar a un acuerdo?",
    img: getImage(8),
    date: "2023-04-14",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Víctor Vázquez", "Lino Carrillo"],
    links: ["https://www.youtube.com/watch?v=wURy9K7qnf0"],
  },
  {
    name: "La Liturgia Petrolera",
    img: getImage(9),
    date: "2023-03-31",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Luis Pacheco"],
    links: ["https://www.youtube.com/watch?v=wURy9K7qnf0"],
  },
  {
    name: "¿Invertir en un Activo Petrolífero?",
    img: getImage(10),
    date: "2023-03-24",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Oman Oquendo"],
    links: ["https://www.youtube.com/watch?v=TaF7deFEbI8"],
  },
  {
    name: "Son los hidrocarburos una maldición o una bendición para el mundo?",
    img: getImage(11),
    date: "2023-03-17",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Julián Salazar Velásquez"],
    links: ["https://www.youtube.com/watch?v=AEXo8fRJYAA"],
  },
  {
    name: "Campo Zuata-RETOS PARA LA EVENTUAL REACTIVACIÓN",
    img: getImage(0),
    date: "2023-03-10",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Adriano Celli"],
    links: ["https://www.youtube.com/watch?v=Sqv_5m4avEs"],
  },
  {
    name: "La Nacionalización Petrolera en la Gran Venezuela",
    img: getImage(1),
    date: "2023-03-03",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gerardo Lucas"],
    links: ["https://www.youtube.com/watch?v=1oZanBRQCgE"],
  },
  {
    name: "Petróleo y sociedad venezolana: una conexión distante",
    img: getImage(2),
    date: "2023-02-24",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Guillermo Guzmán Mirabal"],
    links: ["https://www.youtube.com/watch?v=jX4nI8mC-W4"],
  },
  {
    name: "Venezuela, energía y post socialismo",
    img: getImage(3),
    date: "2023-02-17",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["David Morán Bohórquez"],
    links: ["https://www.youtube.com/watch?v=fcjpi8oi3ag"],
  },
  {
    name: "Transición energética, los ESG's y los desafíos competitivos. Una visión regional",
    img: getImage(4),
    date: "2023-02-09",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Fernando H. Branger G."],
    links: ["https://www.youtube.com/watch?v=uUEs13rOtZQ"],
  },
  {
    name: "Una Fábrica de Ciudadanos, Bases para la reconstrucción de Venezuela",
    img: getImage(5),
    date: "2023-02-03",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gustavo Coronel"],
    links: ["https://www.youtube.com/watch?v=HAi7smbtdkQ"],
  },
  {
    name: "Visión del Sistema Eléctrico Nacional",
    img: getImage(6),
    date: "2023-01-27",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gustavo González", "Alberto De Lima"],
    links: ["https://www.youtube.com/watch?v=XNQn78K5Jjo"],
  },
  {
    name: "Comunicación No Violenta",
    img: getImage(7),
    date: "2023-01-21",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["María E. Garassini"],
    links: ["https://www.youtube.com/watch?v=t59tQNitsYI"],
  },
];
