import type { LibraryEvent } from "./types";
import { getImage } from "./images";

export const events2024: LibraryEvent[] = [
  {
    name: "El país que queremos",
    img: getImage(0),
    date: "2024-12-22",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Rafael de la Cruz"],
    links: ["https://www.youtube.com/watch?v=MUD30syDIbU"],
  },
  {
    name: "Venezuela - Camino al Futuro",
    img: getImage(1),
    date: "2024-12-06",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Dr. R. Evan Ellis"],
    links: ["https://youtu.be/_NuVMFkbZZ4"],
  },
  {
    name: "Ganó Trump!!! Cómo puede impactar eso en Venezuela?",
    img: getImage(2),
    date: "2024-11-15",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Casto Ocando"],
    links: ["https://youtu.be/HHAgaP8Sp74"],
  },
  {
    name: "El Poder de la Gente en el Renacimiento de Venezuela.",
    img: getImage(3),
    date: "2024-11-08",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Tomás Mata"],
    links: ["https://youtu.be/NVaKnaKsQH0"],
  },
  {
    name: "Computación en la nube. Oportunidades de negocios y desafíos.",
    img: getImage(4),
    date: "2024-11-01",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["William R. Colina"],
    links: ["https://youtu.be/CcdqW27hTaw"],
  },
  {
    name: "La inversión en Infraestructura un desafío costoso pero impostergable",
    img: getImage(5),
    date: "2024-10-25",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["José María de Viana"],
    links: ["https://youtu.be/UOGDYR9Kb-M"],
  },
  {
    name: "Amaneció Temprano- Historia de dos Venezuelas",
    img: getImage(6),
    date: "2024-10-18",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Alberto Rial"],
    links: ["https://youtu.be/e6N7vTt8NjI"],
  },
  {
    name: "Venezuela a futuro",
    img: getImage(7),
    date: "2024-10-11",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Dra. Sary Levy Carciente"],
    links: ["https://youtu.be/aDohCFTJS2w"],
  },
  {
    name: "VENEZUELA PETROLERA: SEIS CUENTOS Y TRES REMORDIMIENTOS",
    img: getImage(8),
    date: "2024-09-27",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Rafael Gallegos"],
    links: ["https://youtu.be/_3dZBXioG6E"],
  },
  {
    name: "¿Son las reservas de petróleo y gas de Venezuela cruciales para la seguridad a largo plazo del hemisferio occidental?",
    img: getImage(9),
    date: "2024-09-20",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Evanan Romero"],
    links: ["https://youtu.be/2rlxIcfbews"],
  },
  {
    name: "Propuesta para un Desarrollo Forestal Diversificado y sostenible",
    img: getImage(10),
    date: "2024-09-13",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["OMAR CARRERO N."],
    links: ["https://youtu.be/DFgAl7VZkEo"],
  },
  {
    name: "Análisis del Potencial Energético de Yacimientos No Convencionales en América del Norte y Venezuela.",
    img: getImage(11),
    date: "2024-09-06",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Douglas Betancourt"],
    links: ["https://youtu.be/htP92aRnZsc"],
  },
  {
    name: "El Bien y el Mal: la lucha eterna examinada a través de Los Monstruos de la Literatura.",
    img: getImage(0),
    date: "2024-08-23",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["María Dolores Ara Díaz"],
    links: ["https://youtu.be/5wzXSm5ij-w"],
  },
  {
    name: "Situación Actual del Mercado Petrolero Mundial",
    img: getImage(1),
    date: "2024-08-16",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Carlos Rossi"],
    links: ["https://youtu.be/MIaJkFOs4dw"],
  },
  {
    name: "Implicaciones de los Resultados Electorales de Venezuela.",
    img: getImage(2),
    date: "2024-08-02",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Dr. R. Evan Ellis"],
    links: ["https://youtu.be/pXvujskff54"],
  },
  {
    name: "AMPP y su gestión global contra la corrosión. Pasado, presente y futuro para Venezuela",
    img: getImage(3),
    date: "2024-07-26",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Romer Gil"],
    links: ["https://youtu.be/U5kyayw0qTc"],
  },
  {
    name: "Desafíos del Marketing Digital 2024 y Escenarios Futuros",
    img: getImage(4),
    date: "2024-07-19",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Gabriel Angulo y Santiago Rodríguez Reggeti"],
    links: ["https://youtu.be/jI7bRgHvyc8"],
  },
  {
    name: "¿CÓMO APROVECHAR EL INCOMPARABLE POTENCIAL ENERGÉTICO DE VENEZUELA PARA PROPULSAR SU DESARROLLO?",
    img: getImage(5),
    date: "2024-07-12",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Tomás Mata"],
    links: ["https://youtu.be/K1uU0YmjTTo"],
  },
  {
    name: "El espíritu del 5 de Julio - Venezuela en la Antesala de la Historia",
    img: getImage(6),
    date: "2024-07-05",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Dr. Asdrúbal Aguiar"],
    links: ["https://youtu.be/iNTw3lpKkh8?si=m05MJou8105aEt5P"],
  },
  {
    name: "DISTOPÍAS PROFÉTICAS",
    img: getImage(7),
    date: "2024-06-28",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["María Dolores Ara Díaz"],
    links: ["https://youtu.be/XCbrLzd-M0g"],
  },
  {
    name: "Cómo aprender en la era digital usando técnicas de la Inteligencia Artificial",
    img: getImage(8),
    date: "2024-06-21",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Jonás Montilva"],
    links: ["https://www.youtube.com/watch?v=ohpuggEyOQ4"],
  },
  {
    name: "Más allá de lo Convencional: Evolución y Futuro de los Recursos No Convencionales",
    img: getImage(9),
    date: "2024-06-14",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Oman Oquendo"],
    links: ["https://youtu.be/bbMcLq7IlA8"],
  },
  {
    name: "Venezuela, energía y desarrollo",
    img: getImage(10),
    date: "2024-06-07",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["David Morán"],
    links: ["https://youtu.be/ZFgWSchadkU?si=WF8VA6Mc4xzkSXM0"],
  },
  {
    name: "Emprendimiento Social, clave para el crecimiento sostenible de Venezuela",
    img: getImage(11),
    date: "2024-05-31",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Medardo Mora"],
    links: ["https://youtu.be/H5j_zZqjdeo?si=gaXLoWBUNBMJ2SUO"],
  },
  {
    name: "La Guerra por el Talento en Venezuela",
    img: getImage(0),
    date: "2024-05-24",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Jesús Castillo"],
    links: ["https://youtu.be/88bM0cWSfhc"],
  },
  {
    name: "Posibilidad de apoyo de la DFC al desarrollo futuro económico, social y ambiental de Venezuela",
    img: getImage(1),
    date: "2024-05-17",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Juan Urich"],
    links: ["https://youtu.be/wNY5eUfDYEs"],
  },
  {
    name: "Inteligencia Artificial Generativa: ¿Cómo aprender en la era digital?",
    img: getImage(2),
    date: "2024-05-10",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Jonás A. Montilva C."],
    links: ["https://youtu.be/Uk2H2ElAPXQ"],
  },
  {
    name: "Monetizando tu emprendimiento",
    img: getImage(3),
    date: "2024-05-03",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Edgar Peláez"],
    links: ["https://youtu.be/oR03vqUUenI"],
  },
  {
    name: "La dolarización de la economía venezolana en un nuevo gobierno",
    img: getImage(4),
    date: "2024-04-26",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Gustavo García"],
    links: ["https://youtu.be/4OqIxJQjH9U"],
  },
  {
    name: "Matriz FODA sector energético venezolano",
    img: getImage(5),
    date: "2024-04-19",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Elizabeth Cruz"],
    links: ["https://youtu.be/0LYoB9MGKns"],
  },
  {
    name: "Reporte Especial CERAWeek 2024 by S&P Global, Revista Petroleum",
    img: getImage(6),
    date: "2024-04-12",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Jorge Zajía, Edgar Peláez y Carlos Sanchez"],
    links: ["https://youtu.be/RgG-C0wjxtY"],
  },
  {
    name: "Perspectivas de la producción petrolera en Venezuela",
    img: getImage(7),
    date: "2024-04-05",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Francisco Monaldi"],
    links: ["https://youtu.be/aFXaTeLdTVA"],
  },
  {
    name: "Oportunidades de desarrollo del gas natural bajo una nueva concepción política y económica del País",
    img: getImage(8),
    date: "2024-03-22",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Evanan Romero, Domingo Marsiccobetre y Jesús Aboud"],
    links: ["https://youtu.be/kTmwxgnj_ns"],
  },
  {
    name: "¿Cómo apoyar a los estudiantes universitarios venezolanos?",
    img: getImage(9),
    date: "2024-03-15",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 11PM Venezuela",
    presenters: ["Maria Beatriz de Santa Anna y Alfonso Quaglia"],
    links: ["https://youtu.be/W5trFV3l7N8"],
  },
  {
    name: "La Impostergable reinstitucionalización en Venezuela",
    img: getImage(10),
    date: "2024-03-08",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gonzalo Oliverosz"],
    links: ["https://youtu.be/WGA9fI9_pKM"],
  },
  {
    name: "La Tecnología en la Transición Energética",
    img: getImage(11),
    date: "2024-03-01",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Nelson Hernández"],
    links: ["https://youtu.be/_8YWj5McSgg"],
  },
  {
    name: "El programa de gobierno de MCM",
    img: getImage(0),
    date: "2024-02-23",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Rafael de la Cruz"],
    links: ["https://youtu.be/xbY0rcwBvJA"],
  },
  {
    name: "Preguntas y dilemas sobre el presente y futuro de Venezuela",
    img: getImage(1),
    date: "2024-02-16",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gerver Torres"],
    links: ["https://youtu.be/0fRIlnC-sTQ"],
  },
  {
    name: "Un Vistazo a la Geopolítica en América en 2024",
    img: getImage(2),
    date: "2024-02-09",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["David Morán"],
    links: ["https://youtu.be/v0t3ehkNvRc"],
  },
  {
    name: "ESEQUIBO Y SU PETRÓLEO",
    img: getImage(3),
    date: "2024-02-02",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Jesús Aboud"],
    links: ["https://youtu.be/pSqM2cR8eAo"],
  },
  {
    name: "Las verdades de CITGO y el Gobierno Interino",
    img: getImage(4),
    date: "2024-01-26",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Orlando Viera-Blanco"],
    links: ["https://youtu.be/rYFL_HynKrY"],
  },
  {
    name: "Fundación Simón Bolívar. Creando impacto, mejorando la salud de los venezolanos",
    img: getImage(5),
    date: "2024-01-19",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Mariela Poleo"],
    links: ["https://youtu.be/lDjwDOMyumk"],
  },
];
