import type { LibraryEvent } from "./types";
import { getImage } from "./images";

export const events2025: LibraryEvent[] = [
  {
    name: "Anaco Rejuvenece. Más gas para alimentar hogares y dinamizar el sector industrial",
    img: getImage(0),
    date: "2025-12-12",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Tomás Mata"],
    links: ["https://www.youtube.com/watch?v=QaBeRr6Sx9w"],
  },
  {
    name: "Tecnología Química RDV® Reactor Dinámico Vasoactivo",
    img: getImage(1),
    date: "2025-12-05",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["William Jiménez C"],
    links: ["https://www.youtube.com/watch?v=Pv1jhTfeWmM"],
  },
  {
    name: "El Poder, ¿Volar o arrastrarse?",
    img: getImage(2),
    date: "2025-11-21",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Aquímedes Román"],
    links: ["https://www.youtube.com/watch?v=SyqmiwyyYJw"],
  },
  {
    name: "Bioética y Derechos Humanos",
    img: getImage(3),
    date: "2025-11-14",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Dr Gabriel D'Ampare"],
    links: ["https://www.youtube.com/watch?v=CvlDdc-nvYU"],
  },
  {
    name: "Declina la producción de shale oil en USA Una oportunidad para Venezuela",
    img: getImage(4),
    date: "2025-11-07",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Evanán Romero"],
    links: ["https://www.youtube.com/watch?v=fAI8JrO5KC0"],
  },
  {
    name: "Una estrategia para Venezuela del Asistencialismo al Mercado",
    img: getImage(5),
    date: "2025-10-31",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Benjamin Trapier"],
    links: ["https://www.youtube.com/watch?v=SLbKhgqVGKs"],
  },
  {
    name: "Significado de privatizar en Venezuela",
    img: getImage(6),
    date: "2025-10-24",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["José Manuel Andrade-Cuadra"],
    links: ["https://www.youtube.com/watch?v=CMkfoEHtrA0"],
  },
  {
    name: "IA Riesgos y Oportunidades",
    img: getImage(7),
    date: "2025-10-10",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Vladimiro Mujica"],
    links: ["https://www.youtube.com/watch?v=KKk-3kOr8hA"],
  },
  {
    name: "Las Perlas del Caribe Del Pozo a la Arepa",
    img: getImage(8),
    date: "2025-10-03",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Tomás Mata"],
    links: ["https://www.youtube.com/watch?v=MKZRdLDuE1g"],
  },
  {
    name: "Lo que el CAIDI puede hacer por los migrantes venezolanos",
    img: getImage(9),
    date: "2025-09-26",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Edda Caputto"],
    links: ["https://www.youtube.com/watch?v=QzRAqDF4eAk"],
  },
  {
    name: "Uso de nanofluidos en la producción de petróleo",
    img: getImage(10),
    date: "2025-09-19",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Claudio Martínez"],
    links: ["https://www.youtube.com/watch?v=ROL1pVhp2YU"],
  },
  {
    name: "CITGO Piedra angular para los primeros años de la Transición",
    img: getImage(11),
    date: "2025-09-12",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Horacio Medina"],
    links: ["https://www.youtube.com/watch?v=aScV7ByG374"],
  },
  {
    name: "Inteligencia Artificial a tu alcance",
    img: getImage(0),
    date: "2025-09-05",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Adem M. Wulff"],
    links: ["https://www.youtube.com/watch?v=-KoumDmf0sc"],
  },
  {
    name: "Desarrollo de la IPN mediante estrategias de tercerización",
    img: getImage(1),
    date: "2025-08-29",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Armando R. Carrillo"],
    links: ["https://www.youtube.com/watch?v=GAjclXdknwk"],
  },
  {
    name: "INTELIGENCIA ARTIFICIAL, De la curiosidad al uso inteligente",
    img: getImage(2),
    date: "2025-08-22",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Oviedo Perera Moser"],
    links: ["https://www.youtube.com/watch?v=3EkwD8Xnojc"],
  },
  {
    name: "La solvencia financiera del Estado Venezolano",
    img: getImage(3),
    date: "2025-08-15",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gustavo García"],
    links: ["https://www.youtube.com/watch?v=_vkRU0J6kVI"],
  },
  {
    name: "Las dos tecnologías probadas que cambiarían a futuro el perfil productivo de la Faja del Orinoco",
    img: getImage(4),
    date: "2025-08-08",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Evanán Romero"],
    links: ["https://www.youtube.com/watch?v=FqALHMUoOhA"],
  },
  {
    name: "Potencialidad de Venezuela",
    img: getImage(5),
    date: "2025-07-18",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Sary Levy Carciente"],
    links: ["https://www.youtube.com/watch?v=a6wmT2bvLAQ"],
  },
  {
    name: "La empresa y su transformación digital asistida por IA",
    img: getImage(6),
    date: "2025-07-11",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Jonás A. Montilva"],
    links: ["https://www.youtube.com/watch?v=uq-m0bxDqIo"],
  },
  {
    name: "Hidrocarburos Venezolanos, esperanza nacional y necesidad mundial",
    img: getImage(7),
    date: "2025-06-27",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Juan Szabo"],
    links: ["https://www.youtube.com/watch?v=Zb3qQyYPeTk"],
  },
  {
    name: "Inteligencia artificial en el sector energético",
    img: getImage(8),
    date: "2025-06-20",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["GEORGE TABORDA"],
    links: ["https://www.youtube.com/watch?v=LCePQYCGSfk"],
  },
  {
    name: "Cómo usar el Poder Transformador del Petróleo para Erradicar la Pobreza",
    img: getImage(9),
    date: "2025-06-13",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["TOMÁS MATA"],
    links: ["https://www.youtube.com/watch?v=7TB7XAHIRd8"],
  },
  {
    name: "VAPAResPro",
    img: getImage(10),
    date: "2025-06-07",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Alfonso Quaglia"],
    links: ["https://www.youtube.com/watch?v=e0agLMWeOWQ"],
  },
  {
    name: "Otros dos Papas Francisco y León XIV",
    img: getImage(11),
    date: "2025-05-31",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Asdrubal Aguiar"],
    links: ["https://www.youtube.com/watch?v=x4_TOF9IxSQ"],
  },
  {
    name: "GERENCIA INTEGRADA DE CAMPOS DE HIDROCARBUROS",
    img: getImage(0),
    date: "2025-05-25",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Julián Salazar Velásquez"],
    links: ["https://www.youtube.com/watch?v=XqiFxhQfaXE"],
  },
  {
    name: "Estatismo en la la Industria Petrolera",
    img: getImage(1),
    date: "2025-05-17",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Evanán Romero"],
    links: ["https://www.youtube.com/watch?v=L8FVvmDAuRE"],
  },
  {
    name: "Cambio organizacional y cultura El caso de Venezuela",
    img: getImage(2),
    date: "2025-05-10",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Alberto Rial"],
    links: ["https://www.youtube.com/watch?v=fyq4cTRwVJw"],
  },
  {
    name: "Confiabilidad Integral de Procesos Productivos",
    img: getImage(3),
    date: "2025-05-03",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Medardo Yañez"],
    links: ["https://www.youtube.com/watch?v=aNjGvOTm-Ts"],
  },
  {
    name: "La electricidad en Venezuela como palanca de cualquier expectativa de un buen futuro",
    img: getImage(4),
    date: "2025-04-27",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Benjamín Tripier"],
    links: ["https://www.youtube.com/watch?v=coTvA0kkhMQ"],
  },
  {
    name: "Propuesta de Un nuevo desarrollo CTI para Venezuela",
    img: getImage(5),
    date: "2025-04-18",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["José Manuel Martínez"],
    links: ["https://youtu.be/Kph_5mkbHOY"],
  },
  {
    name: "El sistema de patentes en USA",
    img: getImage(6),
    date: "2025-04-11",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Carlos Ruiz"],
    links: ["https://youtu.be/Gkwunmltpfc"],
  },
  {
    name: "CERAWEEK 2025 by S&P Global",
    img: getImage(7),
    date: "2025-04-04",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Jorge Zajía", "Edgar Peláez", "Carlos Sánchez", "Tomás Mata"],
    links: ["https://www.youtube.com/watch?v=OZpk0mN19_c"],
  },
  {
    name: "Codicia Auge y declinación de la Cúpula Bancaria en Venezuela 1974 1994",
    img: getImage(8),
    date: "2025-03-21",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Gerardo Lucas"],
    links: ["https://www.youtube.com/watch?v=u264BVIeKbA"],
  },
  {
    name: "SISTEMA INTEGRAL DE OPTIMIZACION DE PRODUCCION POR EFECTOS PULSANTES (SIOP)",
    img: getImage(9),
    date: "2025-03-14",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Henry Pino"],
    links: ["https://www.youtube.com/watch?v=l-dBkoV78dY"],
  },
  {
    name: "Lentes para la miopía petrolera",
    img: getImage(10),
    date: "2025-03-07",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Rafael Gallegos"],
    links: ["https://youtu.be/zOBAdsbq5I4"],
  },
  {
    name: "Caracterización Petrofísica Avanzada",
    img: getImage(11),
    date: "2025-02-28",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Douglas Betancourt"],
    links: ["https://youtu.be/vYd4io8w6_Q"],
  },
  {
    name: "IA: EL ASTEROIDE INTANGIBLE",
    img: getImage(0),
    date: "2025-02-21",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Luis Ismodes"],
    links: ["https://youtu.be/O3Fu6IDQLoA"],
  },
  {
    name: "Renovables y Fósiles: El Futuro de la Energía en Equilibrio",
    img: getImage(1),
    date: "2025-02-14",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Claudio Martínez"],
    links: ["https://youtu.be/nVg0tHf_ZHI"],
  },
  {
    name: "Drill baby, drill",
    img: getImage(2),
    date: "2025-02-07",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Francisco Gamarra", "Tyrone Perdomo", "Evanán Romero"],
    links: ["https://www.youtube.com/watch?v=Q0P7GGoVFTs"],
  },
  {
    name: "Se administran organizaciones, se lideran personas",
    img: getImage(3),
    date: "2025-01-31",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Eduardo Martí F"],
    links: ["https://youtu.be/q-KKKFFHFRg"],
  },
  {
    name: "La Influencia geopolítica del Foro de Sao Paulo",
    img: getImage(4),
    date: "2025-01-24",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Alejandro Peña Esclusa"],
    links: ["https://youtu.be/r_lOLVc89h4"],
  },
  {
    name: "Revolución de la Gerencia Integrada de Yacimiento con el uso de Inteligencia Artificial",
    img: getImage(5),
    date: "2025-01-17",
    type: "webinar",
    time: "Fri 10AM (CT) - 11AM (ET) - 12PM Venezuela",
    presenters: ["Claudio Martínez"],
    links: ["https://www.youtube.com/watch?v=TijV37vdDBc"],
  },
];
